# Generated by Django 5.2.5 on 2025-08-18 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я блогера")),
                ('ref_link_to_site', models.URLField(verbose_name='Реферальне посилання на сайт')),
                ('invited_people', models.IntegerField(default=0, verbose_name='Запрошено людей')),
                ('ref_link_to_bot', models.URLField(verbose_name='Реферальне посилання на бот')),
            ],
            options={
                'verbose_name': 'Блогер',
                'verbose_name_plural': 'Блогери',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст повідомлення')),
                ('media', models.FileField(blank=True, null=True, upload_to='scheduled_media/', verbose_name='Медіа файл')),
                ('send_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час відправки')),
                ('sent', models.BooleanField(default=False, verbose_name='Відправлено')),
            ],
            options={
                'verbose_name': 'Заплановане повідомлення',
                'verbose_name_plural': 'Заплановані повідомлення',
            },
        ),
        migrations.CreateModel(
            name='ScheduledButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='bot.scheduledmessage')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм ID')),
                ('username', models.CharField(max_length=100, verbose_name='Юзернейм')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамілія')),
                ('bloger', models.ManyToManyField(related_name='bloger', to='bot.bloger', verbose_name='Блогер який запросив')),
            ],
        ),
    ]
