# Generated by Django 5.2.5 on 2025-08-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(verbose_name='Телеграм ID'),
        ),
    ]
