# Generated by Django 5.2.5 on 2025-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст повідомлення')),
                ('media', models.FileField(upload_to='', verbose_name='Медіафайл')),
                ('button_text', models.CharField(max_length=32, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
    ]
