# Generated by Django 5.2.5 on 2025-08-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_message_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='button_text',
            field=models.CharField(default=0, max_length=100, verbose_name='Текст кнопки'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScheduledButton',
        ),
    ]
