# Generated by Django 5.2.5 on 2025-08-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_scheduledmessage_button_text_delete_scheduledbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Медіафайл'),
        ),
    ]
