# Generated by Django 5.2.5 on 2025-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='ref_link_to_bot',
            field=models.URLField(blank=True, null=True, verbose_name='Реферальне посилання на бот'),
        ),
    ]
