# Generated by Django 5.2.5 on 2025-08-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_user_options_alter_message_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bloger',
        ),
        migrations.AddField(
            model_name='user',
            name='bloger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='bot.bloger', verbose_name='Блогер який запросив'),
        ),
    ]
