# Generated by Django 5.2.5 on 2025-08-20 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_user_bloger_user_bloger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст повідомлення')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('media', models.FileField(blank=True, null=True, upload_to='scheduled_media/', verbose_name='Медіа файл')),
                ('delay_minutes', models.PositiveIntegerField(default=0, verbose_name='Затримка у хвилинах')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Додався в'),
            preserve_default=False,
        ),
    ]
