# Generated by Django 5.2.5 on 2025-08-20 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_campain_user_joined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campain',
            options={'verbose_name': 'Повідомлення після старту', 'verbose_name_plural': 'Повідомлення після старту'},
        ),
        migrations.CreateModel(
            name='MessageAfterStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст повідомлення')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('media', models.FileField(blank=True, null=True, upload_to='scheduled_media/', verbose_name='Медіа файл')),
                ('send_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час відправки')),
                ('sent', models.BooleanField(default=False, verbose_name='Відправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
    ]
