# Generated by Django 5.2.5 on 2025-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_campain_options_messageafterstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='button_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=xtvX0OXU4QA', verbose_name='Посилання кнопки'),
            preserve_default=False,
        ),
    ]
