# Generated by Django 5.2.5 on 2025-08-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_scheduledmessage_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання кнопки'),
        ),
    ]
