# Generated by Django 5.2.5 on 2025-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_scheduledmessage_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва бота')),
                ('token', models.CharField(max_length=255, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='button_link',
            field=models.URLField(blank=True, help_text="<div style='font-size:14px; color:#999;'>\n            Якщо не вказати посилання, буде використанно реферальне посилання на сайт блогера, який  привів\n            </div>", null=True, verbose_name='Посилання кнопки'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='text',
            field=models.TextField(help_text="<div style='font-size:14px; color:#999;'>Для того щоб у розсилці вказати ім&#x27;я користувача, використайте {name}. Підтримується HTML форматування: &lt;b&gt;жирний&lt;/b&gt;, &lt;i&gt;курсив&lt;/i&gt;.</div>", verbose_name='Текст повідомлення'),
        ),
    ]
