# Generated by Django 5.2.5 on 2025-09-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_bot_alter_scheduledmessage_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боти'},
        ),
        migrations.AddField(
            model_name='bloger',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campain',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageafterstart',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
            preserve_default=False,
        ),
    ]
