# Generated by Django 5.2.5 on 2025-09-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_bot_options_bloger_bot_campain_bot_message_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_id',
            field=models.BigIntegerField(blank=True, help_text='ID визначається автоматично його не потрібно заповнювати', null=True, verbose_name='ID бота'),
        ),
        migrations.AddField(
            model_name='bot',
            name='username',
            field=models.CharField(blank=True, help_text='Юзернейм визначається автоматично', max_length=100, null=True, verbose_name='Юзернейм бота'),
        ),
    ]
