# Generated by Django 5.2.5 on 2025-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_bot_bot_id_bot_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(verbose_name='Телеграм ID'),
        ),
    ]
