# Generated by Django 5.2.5 on 2025-09-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('blocked', 'Заблокував бота'), ('deleted', 'Видалив акаунт'), ('forbidden', 'Інша помилка')], default='active', max_length=20, verbose_name='Статус користувача'),
        ),
    ]
