# Generated by Django 5.2.5 on 2025-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва кнопки для miniapp'),
        ),
        migrations.AddField(
            model_name='bot',
            name='miniapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на сайт для miniapp'),
        ),
    ]
