# Generated by Django 5.2.5 on 2025-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_botstatistics_bot_button_text_bot_miniapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='send_button',
            field=models.BooleanField(default=True, verbose_name='Відправити кнопку'),
        ),
    ]
