# Generated by Django 5.2.5 on 2025-10-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_folder_bot_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='foler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bot.folder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='messageafterstart',
            name='foler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_after_start', to='bot.folder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='foler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to='bot.folder', verbose_name='Папка'),
        ),
    ]
