# Generated by Django 5.2.5 on 2025-10-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_message_foler_messageafterstart_foler_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='foler',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='messageafterstart',
            old_name='foler',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='scheduledmessage',
            old_name='foler',
            new_name='folder',
        ),
    ]
