# Generated by Django 5.2.5 on 2025-10-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_rename_foler_message_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageafterstart',
            name='folder',
        ),
        migrations.AddField(
            model_name='campain',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campains', to='bot.folder', verbose_name='Папка'),
        ),
    ]
