# Generated by Django 5.2.5 on 2025-10-03 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_remove_messageafterstart_folder_campain_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.AlterField(
            model_name='message',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
    ]
