# Generated by Django 5.2.5 on 2025-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_alter_campain_bot_alter_message_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='use_this',
            field=models.BooleanField(default=True, help_text='Якщо не вказати цей параметр буде використовуватись повідомлення яке стоїть для всієї папки', verbose_name='Використовувати це повідомлення?'),
        ),
        migrations.AddField(
            model_name='message',
            name='use_this',
            field=models.BooleanField(default=True, help_text='Якщо не вказати цей параметр буде використовуватись повідомлення яке стоїть для всієї папки', verbose_name='Використовувати це повідомлення?'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='use_this',
            field=models.BooleanField(default=True, help_text='Якщо не вказати цей параметр буде використовуватись повідомлення яке стоїть для всієї папки', verbose_name='Використовувати це повідомлення?'),
        ),
    ]
