# Generated by Django 5.2.5 on 2025-10-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_campain_use_this_message_use_this_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='use_this',
        ),
    ]
