# Generated by Django 5.2.5 on 2025-10-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_remove_scheduledmessage_use_this'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campain',
            name='use_this',
        ),
        migrations.RemoveField(
            model_name='message',
            name='use_this',
        ),
        migrations.AddField(
            model_name='bot',
            name='use_our_messages',
            field=models.BooleanField(default=True, help_text='Якщо не вказати це параметр будуть використовуватись повідомленя які вказані в папці', verbose_name='Використовувати повідомлення бота'),
        ),
    ]
