# Generated by Django 5.2.5 on 2025-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_remove_campain_use_this_remove_message_use_this_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_digits',
            field=models.BooleanField(default=False, help_text='Для того щоб відправилось повідомлення з відліком цифер, потірбно створити друге повідомлення', verbose_name='Відправляти цифри перед посилання'),
        ),
    ]
