# Generated by Django 5.2.5 on 2025-10-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_message_send_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_for_digits',
            field=models.BooleanField(default=False, verbose_name='Використовувати це повідомлення перед відліком цифр?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_digits',
            field=models.BooleanField(default=False, help_text='Для того щоб відправилось повідомлення з відліком цифр, потірбно створити друге повідомлення', verbose_name='Відправляти цифри перед посилання'),
        ),
    ]
