# Generated by Django 5.2.5 on 2025-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_message_message_for_digits_alter_message_send_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='term',
            field=models.BooleanField(default=False, verbose_name='Підтвердження умов'),
        ),
    ]
